spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    #url: jdbc:postgresql://10.140.0.3:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false #jpa가 만들어내는 쿼리가 로그에 남지 않게됨
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.146.0.2
    username: guest
    password: guest
    port: 5672
